apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grpc-client
  namespace: argocd
spec:
  project: grpc-client
  source:
    repoURL: https://github.com/aalmog999/almog-project
    targetRevision: main
    path: utila/argocd/helm
    helm:
      releaseName: grpc-client
      # parameters:
      #   - name: values
      #     value: apps/test-app/test-app-values.yaml
      valueFiles:
        - ../../../utila/argocd/dev/charts/grpc-client/grpc-client-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: utila
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
