{{- if .Values.keda_autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    name: {{ include "service.fullname" . }}
  minReplicaCount: {{ .Values.keda_autoscaling.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda_autoscaling.maxReplicaCount }}
  pollingInterval: {{ .Values.keda_autoscaling.pollingInterval }}
  cooldownPeriod: {{ .Values.keda_autoscaling.cooldownPeriod }}
  triggers:
    {{- toYaml .Values.keda_autoscaling.triggers | nindent 4 }}
{{- end }}