{{- $namespace := .Values.global.namespace -}}
{{- if .Values.deployment.pvcVolumes.enabled }}
{{- range $nameSuffix, $data := .Values.deployment.pvcVolumes.volumes }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "service.name" $ }}-{{ $nameSuffix }}
  {{- if $namespace}}
  namespace: {{ $namespace }}
  {{- else }}
  namespace: {{ template "service.namespace" $ }}
  {{- end }}
  labels:
  {{- include "service.labels" $ | nindent 4 }}
{{- if $data.additionalLabels }}
{{ toYaml $data.additionalLabels | indent 4 }}
{{- end }}
{{- if $data.annotations }}
  annotations:
{{ toYaml $data.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ $data.accessMode | quote }}
  resources:
    requests:
      storage: {{ $data.storageSize | quote }}
{{- if $data.storageClass }}
{{- if (eq "-" $data.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ $data.storageClass }}"
{{- end }}
{{- end }}
{{- if $data.volumeMode }}  
  volumeMode: "{{ $data.volumeMode }}"
{{- end }}
{{- if $data.volumeName }}  
  volumeName: "{{ $data.volumeName }}"
{{- end }}
{{- end }}
{{- end }}
