{{- $namespace := .Values.global.namespace -}}
{{- if .Values.secret.enabled }}
{{- range $nameSuffix, $data := .Values.secret.files }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "service.name" $ }}-{{ $nameSuffix }}
  {{- if $namespace }}
  namespace: {{ $namespace }}
  {{- else }}
  namespace: {{ template "service.namespace" $ }}
  {{- end }}  
  labels:
  {{- include "service.labels" $ | nindent 4 }}
{{- if $data.additionalLabels }}
{{ toYaml $data.additionalLabels | indent 4 }}
{{- end }}
{{- if $data.annotations }}
  annotations:
{{ toYaml $data.annotations | indent 4 }}
{{- end }}
data:
{{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
---
{{- end }}
{{- end }}