{{- $namespace := .Values.global.namespace -}}
{{- if .Values.configMap.enabled }}
{{- range $nameSuffix, $data := .Values.configMap.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service.name" $ }}-{{ $nameSuffix }}
  {{- if $namespace }}
  namespace: {{ $namespace }}
  {{- else }}
  namespace: {{ template "service.namespace" $ }}
  {{- end }}
  labels:
  {{- include "service.labels" $ | nindent 4 }}
{{- if $data.additionalLabels }}
{{ toYaml $data.additionalLabels | indent 4 }}
{{- end }}
{{- if $data.annotations }}
  annotations:
{{ toYaml $data.annotations | indent 4 }}
{{- end }}
data:
{{ include "service.tplvalues.render" ( dict "value" $data.data "context" $ ) | indent 2 }}
---
{{- end }}
{{- end }}