{{- $namespace := .Values.global.namespace -}}
{{- $ingress := .Values.ingress -}}
{{- if $ingress.enabled -}}
apiVersion: {{ include "service.ingressAPIVersion" . }}
kind: Ingress
metadata:
  name: "{{ include "service.fullname" . }}"
  {{- if $namespace }}
  namespace: {{ $namespace }}
  {{- else }}
  namespace: {{ template "service.namespace" $ }}
  {{- end }}
  {{- with $ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
    {{- range $key, $value := $ingress.labels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- with $ingress.tls }}
    {{- toYaml . | nindent 2 }}
    {{- end }}
  {{- end }}
  ingressClassName: {{ $ingress.className }}
  rules:
    {{- with $ingress.rules }}
    {{- toYaml . | nindent 2 }}
    {{- end }}
{{- end }}
