{{- $root := . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" $root }}

  {{- if $root.Values.global.namespace }}
  namespace: {{ $root.Values.global.namespace }}
  {{- else }}
  namespace: {{ include "service.namespace" $root }}
  {{- end }}

  {{- with $root.Values.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key (tpl ($value | toString) $root | quote) | nindent 4 }}
    {{- end }}
  {{- end }}

  labels:
    {{- include "service.labels" $root | nindent 4 }}
    {{- range $key, $value := $root.Values.service.labels }}
    {{- printf "%s: %s" $key (tpl ($value | toString) $root | quote) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: http

spec:
  type: {{ $root.Values.service.type }}

  {{- if and
    (eq "LoadBalancer" $root.Values.service.type)
    $root.Values.service.loadBalancerIP
  }}
  loadBalancerIP: {{ $root.Values.service.loadBalancerIP }}
  {{- end }}

  {{- if and
    (eq "LoadBalancer" $root.Values.service.type)
    $root.Values.service.loadBalancerSourceRanges
  }}
  loadBalancerSourceRanges:
    {{- toYaml $root.Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}

  {{- with $root.Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}

  {{- with $root.Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  ports:
    {{- if $root.Values.service.extraPorts }}
    {{- toYaml $root.Values.service.extraPorts | nindent 4 }}
    {{- else }}
    - name: {{ $root.Values.service.ports.name }}
      protocol: TCP
      port: {{ $root.Values.service.ports.port }}
      targetPort: {{ $root.Values.service.ports.targetPort }}
    {{- end }}

  selector:
    {{- include "service.selectorLabels" $root | nindent 4 }}